version: '3'
services:
  postgresdb:
    image: postgres:alpine
    container_name: postgresdb
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
        - "5432:5432"

    volumes:
      - postgres-data:/var/lib/postgresql/data

  # rabbitmq:
  #   image: rabbitmq:3.9-management
  #   container_name: rabbit
  #   ports:
  #       - 5672:5672
  #       - 15672:15672

volumes:
  postgres-data:
